---
apiVersion: awx.ansible.com/v1
kind: AWX
metadata:
  name: awx
---
apiVersion: v1
kind: Secret
metadata:
  name: <resourcename>-admin-password
  namespace: <target namespace>
stringData:
  password: mysuperlongpassword
