--- 
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata: 
  name: awx
  namespace: dev
  
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: dev
stringData:
  password: test
