---
apiVersion: awx.ansible.com/v1
kind: AWX
metadata:
  name: awx
---
spec:
  tower_web_resource_requirements:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  tower_task_resource_requirements:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
