---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
stringData:
  host: postgresql.poc-aci-1.svc.cluster.local
  port: '5432'
  database: awx
  username: awx
  password: awx
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: dev
spec:
  deployment_type: awx
  tower_replicas: 1
  tower_admin_user: admin
  tower_admin_email: username@domain.com
  tower_admin_password: superduperpassword
  tower_broadcast_websocket_secret: superduperpassword
  tower_ingress_type: Route
  tower_hostname: awx.apps.domain.lab.app
  tower_task_image: ansible/awx:15.0.1 # replace this with desired image
  tower_web_image: ansible/awx:15.0.1 # replace this with desired image
  tower_postgres_image: postgres:10 # replace this with the desired image
  tower_postgres_storage_class: thin
